
### GET '/catalog' root with https
GET https://localhost:7245/catalog

### GET '/catalog/ root with http
GET http://localhost:5005/catalog

### GET '/catalog/1234 root with https
GET https://localhost:7245/catalog/1

### POST a new Item to the Catalog collection
POST https://localhost:7245/catalog
Content-Type: application/json

{
  "id": 23,
  "name": "Shoes",
  "description": "OSU Shoes",
  "brand": "Nike",
  "price": 29.99,
  "ratings": [
    
  ]
}

### POST a new rating to an Item in the Catalog collection
POST https://localhost:7245/catalog/1/ratings
Content-Type: application/json

{
  "id": 1,
  "stars": 3,
  "userName": "Test",
  "review": "Test"
}

### PUT an update to an item based on its ID
PUT https://localhost:7245/catalog/1
Content-Type: application/json

{
  "name": "Ohio State Shirt",
  "description": "Shirt",
  "brand": "Nike",
  "price": 79.99,
  "ratings": [
    {
      "id": 2,
      "stars": 1,
      "userName": "Test",
      "review": "Tests"
    }
  ]
}

### DELETE an update to an item based on its ID
DELETE https://localhost:7245/catalog/3
Content-Type: application/json

### Get token from Auth0
curl --request POST \
  --url https://dev-dk-8282g.us.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"gFi0dxolb9ejhDuIkLCbIkzxkzCWkJk4","client_secret":"w2OXfVmpFihgSbU6lXSOwSLzynr44sFI5zyFczWOZkE50PUb105TWNRB8DPcqLPk","audience":"https://blue-cup","grant_type":"client_credentials"}'
